keys:
  # Users
  - users:
    - &zebradil age188h98rs643kglmetvqt3hhnllw0ga45jg94p8xar2qe0c987k59q9qxv3v
  # Hosts
  - hosts:
    - &tuxedo age1cmdzxa6lymudn9jacup5nph3qdzcjea6s6nlp2xw6mg7jwsscqtsez5naa
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *tuxedo
      - *zebradil
